server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /home/mikasa/project/help_each_other/images
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/help_other?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          #连接池可以分配的最大连接数
          max-active: 8
          #可以连接的最大连接数
          max-idle: 8
          #连接池资源耗尽，尝试连接阻塞时间，负值为无限期阻塞
          max-wait: -1ms
          #连接池最小空闲连接数
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql
  global-config:
    db-config:
      table-prefix: help_
      logic-delete-field: deleted_at
logging:
  level:
    root: info
app:
  config:
    #每页大小
    #pageSize: 10
    imageUrl: http://192.168.1.113/images/
    jwt:
      #token头
      tokenHeader: Authorization
      #生存时间
      ttl: 600000 #10分钟
      #记住登录后的生存时间
      remember: 604800000 #7天
    ignores:
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
        - "/api/auth/register"
        - "/api/upload"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"